### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sh-Amir** [aaronpk/sign-in-with-apple-example#2]
Hi Aaron, 

I tried to run your sample code, so I followed the instruction as you mentioned, but when I clicked the sign in button I got an error message that is said "Your request could not be completed because of an error. Please try again later". do you have any Idea about this error? 

Thank you in advance

**Comment by aaronpk** [comment]
This is a generic error from Apple that is usually caused by some misconfiguration. Double check that you've followed all the steps outlined in this blog post exactly.

https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple
