### ISSUE TITLE
invalid_request

### ISSUE THREAD

**Issue by MarNwk** [aaronpk/sign-in-with-apple-example#3]
Hey, I used your code for testing purposes and it worked. Within the last few days I received this:
![Screenshot 2019-08-23 at 17 30 17](https://user-images.githubusercontent.com/45692346/63604432-ff135200-c5cb-11e9-8204-94fcf2e9130f.png)

I had to add `'response_mode' => 'form_post'` in the $authorize_url to fix it.

**Comment by aaronpk** [comment]
oh no, I saw some comments they were going to be disabling the redirect based flow, I guess it's fine to dive back in and see what they've done.

**Comment by MarNwk** [comment]
Do you remember where you saw the comments if so could you provide a link for me I would like to stay up to date about this topic :)?

**Comment by aaronpk** [comment]
I believe it was this thread on the apple forums: https://forums.developer.apple.com/message/365867

**Comment by MarNwk** [comment]
I also found something directly from apple staff : https://forums.developer.apple.com/thread/121760

**Comment by aaronpk** [comment]
Thanks! I've updated the code to match, and am working on updating the blog post as well!

**Comment by MarNwk** [comment]
@aaronpk You're welcome! I'm happy to help. Thanks for the fast reply and fix :blush:
