### ISSUE TITLE
Error getting an access token

### ISSUE THREAD

**Issue by primeviltom** [aaronpk/sign-in-with-apple-example#6]
Great tutorial! 

I am trying to implement apple sign in for an app (currently in testflight), which also has a web login component which I am trying to get working. 

The apple sign in OAuth flow seems to go OK, but the response I get back from the auth / token is a:

stdClass Object
(
    [error] => invalid_client
)

https://imgur.com/a/R19oRks

I believe my $client id, $client_secret and $redirect_uri are all correct, as this will cause errors earlier in the Auth flow if they are not set correctly. 

Is there anything I might be missing? my php demo can be found at: https://thesnowylist.com.au/appleSignIn.php

Thanks again for a well made tutorial.

**Comment by aaronpk** [comment]
This likely means your client secret is wrong, as the token request is the first time it's used. That's the hardest part of the setup since it requires setting a bunch of properties and making the JWT. Double check that you've got the team ID and client ID and key ID all set properly.

**Comment by primeviltom** [comment]
Thanks for the reply! 

I've double checked my team ID, service identifier (aka "client ID" for web apple sign in) and key ID

I've been using a pure PHP solution to generate the JWT, as I don't have ruby installed on my shared hosting. I'm familiar with creating JWTs for signing push notifications - the structure of that JWT is almost identical to the JWT that is required for apple sign in, the only difference being 3 extra required fields in $claims for apple sign in. I'm using the following code to generate the JWT using my key:

```

<?php
$keyfile = '/home/thesn142/keys/AuthKey_B4GQ6S6M2V.p8';
$keyid = 'B4GQ6S6M2V';
$teamid = 'T6NP2A4T7T';
$client_id = 'au.com.thesnowylist-web'; //service identifier

$key = openssl_pkey_get_private('file://'.$keyfile);

$header = ['alg'=>'ES256','kid'=>$keyid];
$claims = ['iss'=>$teamid,'iat'=>time(), 'exp' => (time() + (86400*14)), 'aud' => 'https://appleid.apple.com', 'sub' => $client_id];
$header_encoded = rtrim(strtr(base64_encode(json_encode($header)), '+/', '-_'), '=');
$claims_encoded = rtrim(strtr(base64_encode(json_encode($claims)), '+/', '-_'), '=');
$signature = ''; 
openssl_sign($header_encoded . '.' . $claims_encoded, $signature, $key, 'sha256');
$jwt = $header_encoded . '.' . $claims_encoded . '.' . base64_encode($signature);

$file = '/home/thesn142/public_html/appleSignIn.jwt';
file_put_contents($file, $jwt)

?>
```

I know you use ruby to create and sign your JWT, but there would be any chance to see if my php version works for you?

**Comment by aaronpk** [comment]
I do have a [PHP example](https://github.com/aaronpk/sign-in-with-apple-example/blob/master/client-secret.php) in the repo, but it uses a JWT library instead of doing it manually.

Looking at your code, it looks like you're using `base64_encode` for the signature instead of base64-url-encoding it. I'd pull out your `rtrim(strtr(base64_encode(json_encode($header)), '+/', '-_'), '=')` code into a function and call it `base64_urlencode` so that you can use it for all three parts.

**Comment by primeviltom** [comment]
I will have a look your PHP example... I've updated my code but no success, still invalid_client...:

```
$keyfile = '/home/thesn142/keys/AuthKey_B4GQ6S6M2V.p8';
$keyid = 'B4GQ6S6M2V';
$teamid = 'T6NP2A4T7T';
$client_id = 'au.com.thesnowylist-web';

$key = openssl_pkey_get_private('file://'.$keyfile);

$header = ['alg'=>'ES256','kid'=>$keyid];
$claims = ['iss'=>$teamid,'iat'=>time(), 'exp' => (time() + (86400*14)), 'aud' => 'https://appleid.apple.com', 'sub' => $client_id];
// $header_encoded = rtrim(strtr(base64_encode(json_encode($header)), '+/', '-_'), '=');
// $claims_encoded = rtrim(strtr(base64_encode(json_encode($claims)), '+/', '-_'), '=');

$header_encoded = base64url_encode(json_encode($header));
$claims_encoded = base64url_encode(json_encode($claims));
$signature = ''; 
openssl_sign($header_encoded . '.' . $claims_encoded, $signature, $key, 'sha256');
$jwt = $header_encoded . '.' . $claims_encoded . '.' . base64url_encode($signature);

$file = '/home/thesn142/public_html/appleSignIn.jwt';
file_put_contents($file, $jwt);


function base64url_encode($data) { 
  return rtrim(strtr(base64_encode($data), '+/', '-_'), '='); 
} 
```

**Comment by aaronpk** [comment]
The next things to try would be to see if the PHP code in this repo works for you, and also to try running the Ruby version on a different computer (MacOS has Ruby built in so that should work) and try using the generated client secret hardcoded into your actual app. If neither of those work, then that points to a problem elsewhere, such as using the wrong value for the `client_id` or some other configuration error in the Apple developer portal.

**Comment by primeviltom** [comment]
Well, the PHP library and ruby scripts work, the issue was with my client_secret - but I'm sure that's no suprise! It's strange that my basic method of signing works for APNs, but not for Apple Sign In.

Thanks for your help mate, very much appreciated!

**Comment by aaronpk** [comment]
No problem! tbh it doesn't surprise me too much, since I'm pretty sure Sign in with Apple is made by a completely different team from the APNS team, and Sign in with Apple seems to have deviated from the OAuth and OIDC standards in ways that make very little sense. Best of luck!

**Comment by Najki** [comment]
@primeviltom  Can you share some details about what was wrong with your `client_secret`? I'm currently having the same issue. Already tried the Ruby and PHP scripts from this repo and triple-checked all the parameters with Apple Developer portal.
